--Captura de errores

-- 1)  REALIZAR UNA DIVISIÓN POR CERO Y ATRAPAR EL ERROR UTILIZANDO VARIABLES DE SISTEMA (REVERTIR LA TRANSACCIÓN). 
BEGIN TRANSACTION
		SELECT 4/0;	
		IF @@ERROR<>0
		BEGIN 
			ROLLBACK TRANSACTION;
			print 'No se puede dividir por cero'
			RETURN; 
		END

COMMIT TRANSACTION
GO


-- 2) REALIZAR UNA DIVISIÓN POR CERO Y ATRAPAR EL ERROR SIN UTILIZAR VARIABLES DE SISTEMA 
--    (REVERTIR LA TRANSACCIÓN).
BEGIN TRY
		BEGIN TRANSACTION
			SELECT 1/0;	
		
		COMMIT TRANSACTION
END TRY
BEGIN CATCH
		ROLLBACK TRANSACTION;
		THROW; 
END CATCH


 -- 3) AGREGAR AL EJERCICIO ANTERIOR EL ENVÍO DE UN MENSAJE DE ERROR UTILIZANDO RAISERROR.
 BEGIN TRY
		BEGIN TRANSACTION
			SELECT 1/0;	
		COMMIT TRANSACTION
END TRY
BEGIN CATCH
		ROLLBACK TRANSACTION;
		RAISERROR (
		            'Aqui el error personalizado ', -- Mensaje personalizado.  
					16, -- Severidad.  
		             1 -- Estado.  
                     ); 
END CATCH



--4)   REALIZAR UNA COPIA DEL PUNTO 3 Y ENVIAR UN MENSAJE DE ERROR UTILIZANDO THROW .
BEGIN TRY
		BEGIN TRANSACTION
			SELECT 1/0;	
		
		COMMIT TRANSACTION
END TRY
BEGIN CATCH
		ROLLBACK TRANSACTION;
		THROW 50001, 'Division por cero no permitida', 1;
END CATCH
